graphhopper:
  datareader.file: /data/argentina-latest.osm.pbf
  graph.location: /data/argentina-gh

  import.osm.ignored_highways: []

  graph.encoded_values: car_access, car_average_speed, country, road_class, roundabout, max_speed, foot_access, foot_average_speed, foot_priority, foot_road_access, hike_rating, bike_access, bike_average_speed, bike_priority, bike_road_access, bike_network, mtb_rating, ferry_speed, road_environment

  profiles:
    - name: car
      custom_model_files: [car.json]
    - name: foot
      custom_model_files: [foot.json]
    - name: bike
      custom_model_files: [bike.json]

  ch.profiles: car

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost